### PR TITLE
fix aviation unit in GECO 2022: "gCO2/pkm" -> "tCO2/pkm"

### LINKED ISSUE #23: bug: align on `aviation` values of `emission_factor_unit`
@cjyetman can you explain specifically what this issue is? 
e.g.: 
For the sector `aviation` we don't know what emissions intensity unit to use, options: `gCO2/pkm` or `...`?

I will try to get an answer :-) 

(Also in general, I would say since the `waldo` regression test passes, this isn't a blocking point for THIS PR, but rather we should open a new issue for it)

_Originally posted by @jdhoffa in https://github.com/RMI-PACTA/pacta.scenario.data.preparation/issues/22#issuecomment-2024910508_

### PR DESCRIPTION
**Pull request by cjyetman**
- closes #23 (I think, because we don't currently have GECO 2021 in this repo)

now this works as expected (with proper input/output paths and `config` properly set)...
```r
source("../workflow.scenario.preparation/process_scenario_geco_2022.R")

pacta.data.validation::validate_intermediate_scenario_output(geco_2022)

waldo::compare(
  dplyr::mutate(
    dplyr::arrange(pacta.scenario.preparation::geco_2022, scenario, scenario_geography, sector, technology),
    units = ifelse(sector == "Aviation", "tCO2/pkm", units)
  ),
  dplyr::arrange(geco_2022, scenario, scenario_geography, sector, technology),
  tolerance = 1e-15
)
```

### CODE REVIEW

**Review by jdhoffa — APPROVED** [review]
lgtm

**Comment by jdhoffa** [comment]
ah wait tests are failing

**Comment by cjyetman** [comment]
had to update test snapshot

note to self: banish snapshot tests

**Review by jdhoffa — APPROVED** [review]
lgtm

**Pull request merged**
