### PR TITLE
add `prepare_weo_2023_scenario()`

### PR DESCRIPTION
**Pull request by cjyetman**
- work towards https://github.com/RMI-PACTA/workflow.scenario.preparation/issues/9
- precedes https://github.com/RMI-PACTA/workflow.scenario.preparation/pull/23

The `weo_2023` object prepared here has some differences with the `pacta.scenario.preparation::weo_2023` object, but I have confirmed with @Antoine-Lalechere that they are probably desirable:
- all Aviation rows in the old version have `NA` for the technology, but the new one has `Passenger`

the following code finds no differences
``` r
waldo::compare(
  dplyr::arrange(pacta.scenario.preparation::weo_2023, scenario, scenario_geography, sector, technology),
  dplyr::mutate(
    dplyr::arrange(weo_2023, scenario, scenario_geography, sector, technology),
    technology = dplyr::if_else(sector == "Aviation", NA, technology)
  )
)
```

### CODE REVIEW

**Review by Antoine-Lalechere — APPROVED** [review]
LGTM

**Review by jdhoffa — APPROVED** [review]
looks grrrrrreeat

**Comment by cjyetman** [comment]
I'm going to force merge because the only changes since your reviews was sorting out the merge conflicts with `sys data.rda` and adding tests for the bridges.

**Comment by jdhoffa** [comment]
Now you can

**Pull request merged**
